service: singapore-cheap-food-api

frameworkVersion: '3'

provider:
  name: google
  stage: prod
  runtime: python39
  region: asia-southeast1
  project: singapore-cheap-food-api
  credentials: ~/.gcloud/keyfile.json
  memorySize: 1024
  timeout: 540s

functions:
  findAddress:
    handler: find_address_handler
    events:
      - http: "GET /find-address"

  getCheapFood:
    handler: get_cheap_food_handler
    events:
      - http: "GET /cheap-food"

plugins:
  - serverless-google-cloudfunctions